### ISSUE TITLE
Request and task details hidden

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#119]
Feedback from user test: request and task details felt hidden below the map. Users felt that they didn't have the necessary context information before looking at the map. Could be helpful to review placement and raise up higher on the page to provide key information quicker to a user. 

![hotosm imagerycoord 2017-06-12 12-04-11](https://user-images.githubusercontent.com/796838/27031234-5aecaec4-4f67-11e7-9345-3ef2b4e291f1.png)

**Comment by smit1678** [comment]
To do here: come up with a new layout to raise the request details up above the map. Not all details may be needed. Priorities are Requesting Organization, Time Period, Product Type, GSD

**Comment by brendangatens** [comment]
I’d maybe like to see the map placed on the right-hand side of the screen so that the request details can be brought up on the left. I’ll mock this up.

**Comment by sharkinsspatial** [comment]
@brendangatens @smit1678 Any ideas on mock ups for this layout?

**Comment by brendangatens** [comment]
@sharkinsspatial here's a crude mockup of a potential layout. I think the map could still be large enough if it were placed on the right-hand side and took up half the width of the screen. We could also make it taller if need be. The request details (Requesting organization etc) could be placed two per row so that the larger text (Purpose/Use/Notes) isn't pushed down too far. The page header (which isn't mocked up fully) could remain the same, but we might want to add a rule to separate this from the body of the request.

![request-task-layout](https://user-images.githubusercontent.com/1270986/30537960-c33e2eaa-9c63-11e7-9d30-e96c96c2db04.png)
