### ISSUE TITLE
Imagery Request App Wireframes

### ISSUE THREAD

**Issue by ascalamogna** [hotosm/imagery-requests#35]
@cgiovando @smit1678 

Attached are the wireframes for your feedback. Please let us know if anything is missing or if this doesn’t reflect anything we talked about. 

The homepage focuses on a dashboard for all requests while the user profile pages focus on the tasks specifically created and assigned by that user. You’ll also see the task and request creation forms which will also be used when editing information later.

Thanks!

**Comment by ascalamogna** [comment]
Correct version of pdf: [wireframes_v1.pdf](https://github.com/hotosm/imagery-requests/files/600820/wireframes_v1.pdf)

**Comment by smit1678** [comment]
Liking the flow and feel thus far. Nice work Anna. 
Couple quick comments: 

* For the request creation view, I expect it'll be just similar to the Task creation, but one of the key user stories was to enable a planner to evaluate existing imagery first before a request is made. Ideas on how we can do that? Ideally we don't make it overly complex but push a user to evaluate first. My thinking is that it is more than just a traditional layer switcher in the corner. 
* really like the landing and the logged in view 
* this is getting into the design but showing the tasks footprints instead of the bbox of the request may be a little more useful view to show progress and completeness.

**Comment by smit1678** [comment]
I put this into Invision to have another look at the flow and feel: https://invis.io/DR9FC80JB#/206976256_Wireframes_V1-pdf_1.

**Comment by danielfdsilva** [comment]
@smit1678 what's your idea in relation to evaluate existing imagery? Isn't the user going to check on other platforms (like oam) for the imagery?

**Comment by smit1678** [comment]
One of the biggest challenges we identified and discussed at SOTM and in Fiji was the need to have a way to bring together a number of map layers -- Bing, Mapbox, DG, OAM -- to be able understand if they will suffice or if a new request needs to be made. Criteria for determining if they will suffice is resolution, cloud cover, availability, age. Pushing them to other platforms doesn't solve the goal of helping them have a tool to evaluate before they make a request. 

An example is when looking at an area, a planner will want to look at the existing layers that are available and compare. Questions they might ask: Which layer is better? Will Mapbox suffice or do I need to look to use the DG layer? If none of the layers are good, do I need to make a request for new imagery?
