### ISSUE TITLE
Benin request: Imagery to support local OSM group

### ISSUE THREAD

**Issue by smit1678** [hotosm/imagery-requests#76]
From imagery-coord list and http://hirc.dev.hotosm.org/requests/30/ via Netherlands Red Cross:

* **Description:** We have been working with a group of local OSM mappers in our projects. They have asked me if I can help them out get better satellite imagery for a local mapping project in Benin. This is the area: http://bl.ocks.org/d/1eacc145e95a80ca6bfe9f91847f9290 They have been asked by the municipality to map these features: - Road map - Health map - School map and - A global map of the municipality

* **Request extent**: http://bl.ocks.org/anonymous/raw/1eacc145e95a80ca6bfe9f91847f9290/

**Comment by smit1678** [comment]
from @pratikyadav [in Slack](https://hotosm.slack.com/archives/imagery-coord/p1485187102000011), need some additional context on the purpose and goal of the local OSM group to map those features. 

Maarten - can you add some text into Slack or here and we can then follow up with @pratikyadav?

**Comment by mjvanderveen** [comment]
The local OSM community is working on developing a good base map for the whole of Benin. They work of Microsoft Bing imagery normally, unless there are areas for which the quality of the imagery is bad, such as this case. The OSM community is very volunteer and humanitarian driven, and they go out to map the country on their own costs. In some cases they work with local municipalities. In this particular case, they have offered the municipality to map the area, so that a open source map of the area is available, that can be used for humanitarian and economical activities. The maps serve to better manage the territory. This partnership with the municipality is important for them to establish themselves as an entity in the country, and to be of added value.

They are going to map roads and buildings through the HOT tasking manger. And in a field mapping, they will add features such as health facilities and schools. They will give the resulting map of the municipality to the local government and the community.

**Comment by amckenna01** [comment]
From the MapGive side we'll have a look at available scenes to support. Tom and I will get back to you.

**Comment by pratikyadav** [comment]
@mjvanderveen Thanks for the information. 👍 
2 quick follow-up questions-
1. Is there any HOT task for this in TM?
2. Would love to understand how Netherlands RC is involved

**Comment by mjvanderveen** [comment]
@pratikyadav 
1. we have not yet created a HOT task for this, since the available Bing Imagery is so bad, that we don't want to publish a task and get people working on it.
2. NLRC is not directly working in this area. Through this request we are trying to strengthen our in-country partner who is doing field mapping for us in other areas. As they have ascertained us that their mapping effort serves a humanitarian purpose, we are happy to help them expand their activities. If you can only provide imagery where NLRC is directly working, then we understand.

We have worked with the local OSM group to map our current project areas fully, which are the complete city of Porto-Novo and the villages of Aguegues and Djambo. For NLRC a good base map is essential for our humanitarian programming. We are actually developing vulnerability algorithms that are working directly of the OSM basemap, to calculate very remote areas. This can gain in strength when the basemap of the whole country is done. As we cannot do this alone, we need in-country partners to continue on the ground work.

**Comment by d3netxer** [comment]
I did a quick assessment and have some follow-up:

- Masse area: The most recent color imagery I am seeing is too cloudy. There is a great panchromatic (black & white) shot that covers most of the area (WV1, DG-ID: 102001004B5D2500, 8 Feb 2016), and another panchromatic of less quality that can cover the remaining areas to the east ( WV1, DG-ID: 102001004913CF00, 1 Jan 2016). I recommend going with these two.

- Bonou area: There is already high-res imagery in OSM, is it too old?

- Pobe area: A recent color shot (WV2, DG-ID: 10300100646AE400, 20 Jan 2017) covers Pobe city. There is about 15-20% cloud cover but I think it can still be useful, especially because their is no high-res imagery in Bing. The remaining areas (Abule Idi and further south), I am not seeing suitable imagery, it is too cloudy. However, Bing imagery has some high-res imagery here that may be adequate?

**Comment by pratikyadav** [comment]
@mjvanderveen  Thanks for the info.

I'll move fwd for this request. I will post here as soon the imagery is live on Mapbox satellite layer. 

cc @d3netxer @smit1678

**Comment by pratikyadav** [comment]
@mjvanderveen  We just rolled out imagery for this request and surrounding areas. Here are some screenshots


![screen shot 2017-02-21 at 3 21 13 pm](https://cloud.githubusercontent.com/assets/12744420/23159683/b7c6deb4-f849-11e6-94de-64e6935b50fc.png)
![screen shot 2017-02-21 at 3 23 18 pm](https://cloud.githubusercontent.com/assets/12744420/23159681/b79e80cc-f849-11e6-8b21-d53c8153263d.png)
![screen shot 2017-02-21 at 3 22 01 pm](https://cloud.githubusercontent.com/assets/12744420/23159680/b78ed32a-f849-11e6-9891-b4c488382d9e.png)
![screen shot 2017-02-21 at 3 21 22 pm](https://cloud.githubusercontent.com/assets/12744420/23159682/b7b73978-f849-11e6-8ddb-1fe25c40128b.png)


Would be great if you can create a project in Tasking Manager. I would love to join the mapping effort. :)

@smit1678  good to close this ticket?

**Comment by smit1678** [comment]
👌  Really nice imagery. Looks great. For reference, what's the date range on this new imagery?

**Comment by pratikyadav** [comment]
@smit1678  Since this is coming from DG's mosaic product; I don't have the exact date.

**Comment by pratikyadav** [comment]
Hi @mjvanderveen @smit1678 

Would love to get an update on the project and how helpful the imagery was for mappers. Do we have any task up that I can follow?
